server:
  port: 8003
spring:
  application:
    name: sentinel-test
  cloud:
    sentinel:
      transport:
        port: 8103
        dashboard: localhost:8899

management:
  endpoints:
    web:
      exposure:
        include: '*'