server:
  port: 8003
spring:
  application:
    name: sentinel-test
  cloud:
    sentinel:
      transport:
        port: 8103
        dashboard: localhost:8899
      datasource: # 持久化sentinel规则
        degrade: # 熔断降级规则数据源配置
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: sentinel-test-degrade
            group-id: SENTINEL_RULES
            data-type: json
            rule-type: degrade  # flow,degrade,authority,system, param-flow
        flow: # 流控规则数据源配置
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: sentinel-test-flow
            group-id: SENTINEL_RULES
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'